# Generated by Django 5.1.7 on 2025-07-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/image.jpg', upload_to='profile_images/'),
        ),
    ]
