# Generated by Django 5.1.7 on 2025-07-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
