# Generated by Django 5.2.4 on 2025-07-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praduc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
