# Generated by Django 5.1.7 on 2025-07-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praduc', '0002_rename_catagory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
